#!/bin/sh

case "$1" in
    start)
        PCA9532_test -BLINK 1 -ALL GREEN
        IMAGE_NAME=`ls /home/*.img`
        dd if=$IMAGE_NAME of=/dev/mmcblk1
        sync
        PCA9532_test -ALL OFF       
        halt
     ;;
     stop)
        echo " "
        echo "Rebooting support system..."
     ;;
esac

exit 0
